### ISSUE TITLE
User name and password doesn't work 

### ISSUE THREAD

**Issue by lgjasmi** [1science/docker-dspace#6]
Hi,

I've installed it. The urls work as expected and every things look good but the user name or password didn't work for me.  I wanted to login as admin using username and password "dspace" it didn't work for me. The system ask for email address not user name. Please if you can help me with this issue It would be grateful.

Thanks.

**Comment by frederik** [comment]
Hi @lgjasmi 

the dspace user and password were the default postgres users. You'll need to [create an admin user](https://wiki.duraspace.org/display/DSDOC6x/Installing+DSpace#InstallingDSpace-InstallationInstructions) (dspace create-administrator). It'll ask you for an email and password.

```
docker ps
docker exec -ti CONTAINERID /dspace/bin/dspace create-administrator
```

Regards
Frederik

**Comment by kaschioudi** [comment]
Hi @frederik, 

I just installed this dspace docker and when I try to create an admin user using the commands above, I get a NullPointerException. Any idea ? 

```
$ sudo docker exec -it e14fa5e5bb0c  /dspace/bin/dspace create-administrator
Creating an initial administrator account
E-mail address: example@domain.com
First name: Kassim
Last name: Machioudi
Password will not display on screen.
Password: 
Again to confirm: 
Is the above data correct? (y or n): y
Exception: null
java.lang.NullPointerException
	at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getColumns(AbstractJdbc2DatabaseMetaData.java:2502)
	at org.postgresql.jdbc4.AbstractJdbc4DatabaseMetaData.getColumns(AbstractJdbc4DatabaseMetaData.java:99)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:218)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:218)
	at org.dspace.storage.rdbms.DatabaseManager.retrieveColumnInfo(DatabaseManager.java:1269)
	at org.dspace.storage.rdbms.DatabaseManager.getColumnInfoInternal(DatabaseManager.java:1212)
	at org.dspace.storage.rdbms.DatabaseManager.getColumnInfo(DatabaseManager.java:810)
	at org.dspace.storage.rdbms.DatabaseManager.getPrimaryKeyColumnInfo(DatabaseManager.java:1100)
	at org.dspace.storage.rdbms.DatabaseManager.getPrimaryKeyColumn(DatabaseManager.java:1082)
	at org.dspace.storage.rdbms.DatabaseManager.find(DatabaseManager.java:505)
	at org.dspace.eperson.Group.find(Group.java:683)
	at org.dspace.administer.CreateAdministrator.createAdministrator(CreateAdministrator.java:234)
	at org.dspace.administer.CreateAdministrator.negotiateAdministratorDetails(CreateAdministrator.java:206)
	at org.dspace.administer.CreateAdministrator.main(CreateAdministrator.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
```

**Comment by frederik** [comment]
Unfortunately I am not familiar enough with the code base to answer that. Does the database exist?

**Comment by kaschioudi** [comment]
> Does the database exist?

yes. postgres database docker image is up and running. I was able to connect to the db and list the tables.

**Comment by frederik** [comment]
hi @kaschioudi - I am posting my docker-compose.yml in the hope that it might boot up for you. I just launched this with clean containers, used localhost:80 (user@domain.com/..) to login to the db admin, checked the dspace db was added and then created an admin user as described above.

I initially had problems with dspace saying it had not connected to the database - a docker-compose restart dspace solved this, though.

(disclaimer: it should hopefully be obvious that these containers neither have a storage volumne attached, nor should these passwords or ports be used in production)

```
version: '2'
services:
  dspace_db:
      image: postgres:9
      environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "example"
      ports:
        - "5432:5432"
  pgadmin:
      image: dpage/pgadmin4
      links:
        - dspace_db
      environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "example"
        PGADMIN_DEFAULT_EMAIL: "user@domain.com"
        PGADMIN_DEFAULT_PASSWORD: "SuperSecret"
      ports:
        - "80:80"
  dspace:
      image: 1science/dspace
      links:
        - dspace_db
      environment:
        POSTGRES_SCHEMA: "dspace"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "example"
        POSTGRES_ADMIN_USER: "user"
        POSTGRES_ADMIN_PASSWORD: "example"
        POSTGRES_DB_HOST: "dspace_db"
      ports:
        - "8080:8080"
```

**Comment by rjcfj** [comment]
I'm really having trouble:
E-mail address: ricardojcfj@gmail.com
First name: Ricardo
Last name: Faria
Password will not display on screen.
Password:
Again to confirm:
Is the above data correct? (y or n): y
Exception: null
java.lang.NullPointerException
        at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getColumns(AbstractJdbc2DatabaseMetaData.java:2502)
        at org.postgresql.jdbc4.AbstractJdbc4DatabaseMetaData.getColumns(AbstractJdbc4DatabaseMetaData.java:99)
        at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:218)
        at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:218)
        at org.dspace.storage.rdbms.DatabaseManager.retrieveColumnInfo(DatabaseManager.java:1269)
        at org.dspace.storage.rdbms.DatabaseManager.getColumnInfoInternal(DatabaseManager.java:1212)
        at org.dspace.storage.rdbms.DatabaseManager.getColumnInfo(DatabaseManager.java:810)
        at org.dspace.storage.rdbms.DatabaseManager.getPrimaryKeyColumnInfo(DatabaseManager.java:1100)
        at org.dspace.storage.rdbms.DatabaseManager.getPrimaryKeyColumn(DatabaseManager.java:1082)
        at org.dspace.storage.rdbms.DatabaseManager.find(DatabaseManager.java:505)
        at org.dspace.eperson.Group.find(Group.java:683)
        at org.dspace.administer.CreateAdministrator.createAdministrator(CreateAdministrator.java:234)
        at org.dspace.administer.CreateAdministrator.negotiateAdministratorDetails(CreateAdministrator.java:206)
        at org.dspace.administer.CreateAdministrator.main(CreateAdministrator.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)

**Comment by frederik** [comment]
Can you share the way you are launching postgres? Does it work for you if you use my docker-compose from above?

**Comment by kaschioudi** [comment]
Hi @frederik ,

Sorry about the late reply. Since running my own DSpace install was giving me too much trouble, I turned to DSpace demo site. Thank you for your reply.

**Comment by frederik** [comment]
@Jedian I've had no such problems with the postgres:9 tag from my docker-compose above (currently pulling 9.6). Just ran a clean docker-compose pull && docker-compose up -d --force-recreate and everything came up smoothly.

**Comment by Jedian** [comment]
@frederik I'm sorry, I was talking about the docker hub [description](https://hub.docker.com/r/1science/dspace/), which suggests the user to run
```
docker run -d --name dspace_db -p 5432:5432 postgres
```
At least for me, this ends up getting the "latest" tag and pulls postgres 10.x, and when this happens, I get the same weird _nullPointerException_ @rjcfj and @kaschioudi had when running `dspace create-administrator`.

I agree with you that using "postgres:9" as a tag can solve this.

Now, about the "string index out of range error", I'm sad for you, but I'm actually a bit happy I'm not the only one.

**Comment by frederik** [comment]
I ended up building dspace 6 from source using this [tutorial](https://github.com/DSpace-Labs/DSpace-Docker-Images/blob/master/tutorial.md) and using the dspace tomcat image as a runner.

While this will not get me a production ready instance in one step its good enough to get more experience with DSpace. You'll have to switch the branch to 6.2 to get the right version, otherwise you build 7 with no UI.
